import type {
  ExerciseKnowledge,
  GymState,
  PerformedSet,
  PlannedSet,
  Program,
  Workout,
  WorkoutExercise,
} from './gym-types';

export const exerciseDatabase: ExerciseKnowledge[] = [
  {
    id: 'bench-press',
    name: 'Barbell Bench Press',
    shortName: 'Bench Press',
    category: 'barbell',
    movementPattern: 'Horizontal press',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Triceps', 'Front delts'],
    equipment: ['Barbell', 'Bench', 'Rack'],
    difficulty: 'intermediate',
    strengthSuitability: 10,
    hypertrophySuitability: 8,
    isMainLift: true,
    similarExerciseIds: ['smith-bench', 'dumbbell-bench', 'machine-chest-press', 'incline-dumbbell-press', 'incline-smith-press'],
  },
  {
    id: 'smith-bench',
    name: 'Smith Machine Bench Press',
    shortName: 'Smith Bench',
    category: 'machine',
    movementPattern: 'Horizontal press',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Triceps', 'Front delts'],
    equipment: ['Smith machine', 'Bench'],
    difficulty: 'beginner',
    strengthSuitability: 7,
    hypertrophySuitability: 9,
    isMainLift: true,
    similarExerciseIds: ['bench-press', 'dumbbell-bench', 'machine-chest-press'],
  },
  {
    id: 'dumbbell-bench',
    name: 'Dumbbell Bench Press',
    shortName: 'DB Bench',
    category: 'dumbbell',
    movementPattern: 'Horizontal press',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Triceps', 'Front delts'],
    equipment: ['Dumbbells', 'Bench'],
    difficulty: 'intermediate',
    strengthSuitability: 7,
    hypertrophySuitability: 9,
    isMainLift: false,
    similarExerciseIds: ['bench-press', 'smith-bench', 'machine-chest-press'],
  },
  {
    id: 'machine-chest-press',
    name: 'Machine Chest Press',
    shortName: 'Chest Press',
    category: 'machine',
    movementPattern: 'Horizontal press',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Triceps', 'Front delts'],
    equipment: ['Chest press machine'],
    difficulty: 'beginner',
    strengthSuitability: 5,
    hypertrophySuitability: 9,
    isMainLift: false,
    similarExerciseIds: ['smith-bench', 'dumbbell-bench', 'bench-press'],
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    shortName: 'Incline DB Press',
    category: 'dumbbell',
    movementPattern: 'Incline press',
    primaryMuscles: ['Upper chest'],
    secondaryMuscles: ['Triceps', 'Front delts'],
    equipment: ['Dumbbells', 'Adjustable bench'],
    difficulty: 'intermediate',
    strengthSuitability: 6,
    hypertrophySuitability: 10,
    isMainLift: false,
    similarExerciseIds: ['incline-smith-press', 'dumbbell-bench', 'machine-chest-press'],
  },
  {
    id: 'incline-smith-press',
    name: 'Incline Smith Machine Press',
    shortName: 'Incline Smith',
    category: 'machine',
    movementPattern: 'Incline press',
    primaryMuscles: ['Upper chest'],
    secondaryMuscles: ['Triceps', 'Front delts'],
    equipment: ['Smith machine', 'Adjustable bench'],
    difficulty: 'beginner',
    strengthSuitability: 6,
    hypertrophySuitability: 9,
    isMainLift: false,
    similarExerciseIds: ['incline-dumbbell-press', 'smith-bench'],
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    shortName: 'Cable Fly',
    category: 'cable',
    movementPattern: 'Horizontal adduction',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Front delts'],
    equipment: ['Cable stack'],
    difficulty: 'beginner',
    strengthSuitability: 2,
    hypertrophySuitability: 10,
    isMainLift: false,
    similarExerciseIds: ['pec-deck', 'dumbbell-fly'],
  },
  {
    id: 'pec-deck',
    name: 'Pec Deck',
    shortName: 'Pec Deck',
    category: 'machine',
    movementPattern: 'Horizontal adduction',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Front delts'],
    equipment: ['Pec deck'],
    difficulty: 'beginner',
    strengthSuitability: 2,
    hypertrophySuitability: 9,
    isMainLift: false,
    similarExerciseIds: ['cable-fly', 'dumbbell-fly'],
  },
  {
    id: 'dumbbell-fly',
    name: 'Dumbbell Fly',
    shortName: 'DB Fly',
    category: 'dumbbell',
    movementPattern: 'Horizontal adduction',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Front delts'],
    equipment: ['Dumbbells', 'Bench'],
    difficulty: 'intermediate',
    strengthSuitability: 2,
    hypertrophySuitability: 7,
    isMainLift: false,
    similarExerciseIds: ['cable-fly', 'pec-deck'],
  },
  {
    id: 'triceps-pushdown',
    name: 'Rope Triceps Pushdown',
    shortName: 'Triceps Pushdown',
    category: 'cable',
    movementPattern: 'Elbow extension',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: [],
    equipment: ['Cable stack', 'Rope'],
    difficulty: 'beginner',
    strengthSuitability: 3,
    hypertrophySuitability: 9,
    isMainLift: false,
    similarExerciseIds: ['close-grip-bench', 'skull-crusher'],
  },
  {
    id: 'close-grip-bench',
    name: 'Close-Grip Bench Press',
    shortName: 'Close-Grip Bench',
    category: 'barbell',
    movementPattern: 'Horizontal press',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: ['Chest', 'Front delts'],
    equipment: ['Barbell', 'Bench', 'Rack'],
    difficulty: 'intermediate',
    strengthSuitability: 8,
    hypertrophySuitability: 8,
    isMainLift: false,
    similarExerciseIds: ['triceps-pushdown', 'bench-press', 'skull-crusher'],
  },
  {
    id: 'skull-crusher',
    name: 'EZ-Bar Skull Crusher',
    shortName: 'Skull Crusher',
    category: 'barbell',
    movementPattern: 'Elbow extension',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: [],
    equipment: ['EZ bar', 'Bench'],
    difficulty: 'intermediate',
    strengthSuitability: 4,
    hypertrophySuitability: 8,
    isMainLift: false,
    similarExerciseIds: ['triceps-pushdown', 'close-grip-bench'],
  },
  {
    id: 'back-squat',
    name: 'Barbell Back Squat',
    shortName: 'Back Squat',
    category: 'barbell',
    movementPattern: 'Squat',
    primaryMuscles: ['Quads', 'Glutes'],
    secondaryMuscles: ['Adductors', 'Spinal erectors'],
    equipment: ['Barbell', 'Rack'],
    difficulty: 'advanced',
    strengthSuitability: 10,
    hypertrophySuitability: 8,
    isMainLift: true,
    similarExerciseIds: ['leg-press', 'front-squat'],
  },
  {
    id: 'front-squat',
    name: 'Front Squat',
    shortName: 'Front Squat',
    category: 'barbell',
    movementPattern: 'Squat',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes', 'Upper back'],
    equipment: ['Barbell', 'Rack'],
    difficulty: 'advanced',
    strengthSuitability: 8,
    hypertrophySuitability: 8,
    isMainLift: true,
    similarExerciseIds: ['back-squat', 'leg-press'],
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    shortName: 'Leg Press',
    category: 'machine',
    movementPattern: 'Squat',
    primaryMuscles: ['Quads', 'Glutes'],
    secondaryMuscles: ['Adductors'],
    equipment: ['Leg press'],
    difficulty: 'beginner',
    strengthSuitability: 5,
    hypertrophySuitability: 9,
    isMainLift: false,
    similarExerciseIds: ['back-squat', 'front-squat'],
  },
  {
    id: 'deadlift',
    name: 'Conventional Deadlift',
    shortName: 'Deadlift',
    category: 'barbell',
    movementPattern: 'Hinge',
    primaryMuscles: ['Glutes', 'Hamstrings', 'Back'],
    secondaryMuscles: ['Forearms', 'Quads'],
    equipment: ['Barbell', 'Plates'],
    difficulty: 'advanced',
    strengthSuitability: 10,
    hypertrophySuitability: 6,
    isMainLift: true,
    similarExerciseIds: ['romanian-deadlift'],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    shortName: 'Romanian Deadlift',
    category: 'barbell',
    movementPattern: 'Hinge',
    primaryMuscles: ['Hamstrings', 'Glutes'],
    secondaryMuscles: ['Back', 'Forearms'],
    equipment: ['Barbell'],
    difficulty: 'intermediate',
    strengthSuitability: 7,
    hypertrophySuitability: 9,
    isMainLift: false,
    similarExerciseIds: ['deadlift'],
  },
];

export const getExercise = (id: string) =>
  exerciseDatabase.find((exercise) => exercise.id === id) ?? exerciseDatabase[0];

const planned = (
  id: string,
  type: PlannedSet['type'],
  targetReps?: number,
  repRange?: [number, number],
  suggestedWeight?: number,
  optional = false,
): PlannedSet => ({ id, type, targetReps, repRange, suggestedWeight, optional });

const performed = (
  id: string,
  type: PerformedSet['type'],
  weight: number,
  reps: number,
  rpe?: number,
  note?: string,
): PerformedSet => ({
  id,
  type,
  weight,
  reps,
  rpe,
  note,
  source: 'manual',
  createdAt: '2026-09-10T18:00:00.000Z',
});

const workoutExercise = (
  id: string,
  exerciseId: string,
  plannedSets: PlannedSet[],
  performedSets: PerformedSet[] = [],
): WorkoutExercise => ({
  id,
  exerciseId,
  plannedSets,
  performedSets,
  status: performedSets.length ? 'complete' : 'pending',
  notes: [],
});

const program: Program = {
  id: 'strength-builder',
  name: 'Strength Builder',
  description: 'Top sets, sensible backoffs, and enough accessories to keep things moving.',
  active: true,
  week: 4,
  days: [
    {
      id: 'push-strength',
      name: 'Push',
      focus: 'Strength',
      estimatedMinutes: 75,
      exercises: [
        { id: 'p1', exerciseId: 'bench-press', label: 'Top set × 3 + 3 backoffs', detail: 'Top set × 3 · Backoff 3 × 5' },
        { id: 'p2', exerciseId: 'incline-dumbbell-press', label: '3 × 8–12', detail: '3 × 8–12' },
        { id: 'p3', exerciseId: 'cable-fly', label: '3 × 10–15', detail: '3 × 10–15', optional: true },
        { id: 'p4', exerciseId: 'triceps-pushdown', label: '3 × 10–15', detail: '3 × 10–15', optional: true },
      ],
    },
    {
      id: 'lower-strength',
      name: 'Lower',
      focus: 'Strength',
      estimatedMinutes: 80,
      exercises: [
        { id: 'l1', exerciseId: 'back-squat', label: 'Top set × 5 + 3 backoffs', detail: 'Top set × 5 · Backoff 3 × 5' },
        { id: 'l2', exerciseId: 'romanian-deadlift', label: '3 × 6–8', detail: '3 × 6–8' },
        { id: 'l3', exerciseId: 'leg-press', label: '3 × 10–12', detail: '3 × 10–12', optional: true },
      ],
    },
    {
      id: 'pull-strength',
      name: 'Pull',
      focus: 'Strength',
      estimatedMinutes: 70,
      exercises: [
        { id: 'd1', exerciseId: 'deadlift', label: 'Top set × 3 + 2 backoffs', detail: 'Top set × 3 · Backoff 2 × 5' },
        { id: 'd2', exerciseId: 'romanian-deadlift', label: '3 × 8', detail: '3 × 8' },
      ],
    },
  ],
};

const makeToday = (): Workout => ({
  id: 'workout-2026-09-13',
  date: '2026-09-13',
  title: 'Push',
  focus: 'Strength',
  estimatedMinutes: 75,
  status: 'planned',
  programDayId: 'push-strength',
  currentExerciseIndex: 0,
  notes: [],
  exercises: [
    workoutExercise('today-bench', 'bench-press', [
      planned('bench-top', 'top_set', 3, undefined, 250),
      planned('bench-backoff-1', 'backoff', 5, undefined, 225),
      planned('bench-backoff-2', 'backoff', 5, undefined, 225),
      planned('bench-backoff-3', 'backoff', 5, undefined, 225),
    ]),
    workoutExercise('today-incline', 'incline-dumbbell-press', [
      planned('incline-1', 'working', undefined, [8, 12], 75),
      planned('incline-2', 'working', undefined, [8, 12], 75),
      planned('incline-3', 'working', undefined, [8, 12], 75),
    ]),
    workoutExercise('today-fly', 'cable-fly', [
      planned('fly-1', 'working', undefined, [10, 15], 40, true),
      planned('fly-2', 'working', undefined, [10, 15], 40, true),
      planned('fly-3', 'working', undefined, [10, 15], 40, true),
    ]),
    workoutExercise('today-triceps', 'triceps-pushdown', [
      planned('tri-1', 'working', undefined, [10, 15], 55, true),
      planned('tri-2', 'working', undefined, [10, 15], 55, true),
      planned('tri-3', 'working', undefined, [10, 15], 55, true),
    ]),
  ],
});

const history: Workout[] = [
  {
    id: 'history-push-0910',
    date: '2026-09-10',
    title: 'Push',
    focus: 'Strength',
    estimatedMinutes: 73,
    status: 'completed',
    programDayId: 'push-strength',
    currentExerciseIndex: 3,
    startedAt: '2026-09-10T17:48:00.000Z',
    completedAt: '2026-09-10T19:01:00.000Z',
    notes: [],
    exercises: [
      workoutExercise('h0910-bench', 'bench-press', [
        planned('h0910-top', 'top_set', 5, undefined, 235),
        planned('h0910-bo1', 'backoff', 5, undefined, 215),
        planned('h0910-bo2', 'backoff', 5, undefined, 215),
        planned('h0910-bo3', 'backoff', 5, undefined, 215),
      ], [
        performed('s1', 'warm_up', 135, 8),
        performed('s2', 'warm_up', 185, 5),
        performed('s3', 'warm_up', 205, 3),
        performed('s4', 'top_set', 235, 5, 8),
        performed('s5', 'backoff', 215, 5),
        performed('s6', 'backoff', 215, 5),
        performed('s7', 'backoff', 215, 5),
      ]),
      workoutExercise('h0910-incline', 'incline-dumbbell-press', [
        planned('i1', 'working', undefined, [8, 12], 75),
        planned('i2', 'working', undefined, [8, 12], 75),
        planned('i3', 'working', undefined, [8, 12], 75),
      ], [
        performed('i1s', 'working', 75, 10),
        performed('i2s', 'working', 75, 9),
        performed('i3s', 'working', 75, 8, undefined, 'Shoulder felt a little pinchy on the final set.'),
      ]),
      workoutExercise('h0910-fly', 'cable-fly', [planned('f1', 'working', undefined, [10, 15])], [
        performed('f1s', 'working', 40, 13),
        performed('f2s', 'working', 40, 12),
        performed('f3s', 'working', 40, 11),
      ]),
      workoutExercise('h0910-tri', 'triceps-pushdown', [planned('t1', 'working', undefined, [10, 15])], [
        performed('t1s', 'working', 55, 15),
        performed('t2s', 'working', 55, 13),
        performed('t3s', 'working', 55, 12),
      ]),
    ],
  },
  {
    id: 'history-lower-0908',
    date: '2026-09-08',
    title: 'Lower',
    focus: 'Strength',
    estimatedMinutes: 79,
    status: 'completed',
    programDayId: 'lower-strength',
    currentExerciseIndex: 2,
    completedAt: '2026-09-08T19:15:00.000Z',
    notes: [],
    exercises: [
      workoutExercise('h0908-squat', 'back-squat', [planned('sqtop', 'top_set', 5, undefined, 405)], [
        performed('sq1', 'warm_up', 135, 8),
        performed('sq2', 'warm_up', 225, 5),
        performed('sq3', 'warm_up', 315, 3),
        performed('sq4', 'top_set', 405, 5, 8),
        performed('sq5', 'backoff', 365, 5),
        performed('sq6', 'backoff', 365, 5),
        performed('sq7', 'backoff', 365, 5),
      ]),
      workoutExercise('h0908-rdl', 'romanian-deadlift', [planned('rdl', 'working', 8)], [
        performed('rdl1', 'working', 245, 8),
        performed('rdl2', 'working', 245, 8),
        performed('rdl3', 'working', 245, 7),
      ]),
    ],
  },
  {
    id: 'history-push-0903',
    date: '2026-09-03',
    title: 'Push',
    focus: 'Volume',
    estimatedMinutes: 68,
    status: 'completed',
    programDayId: 'push-strength',
    currentExerciseIndex: 3,
    completedAt: '2026-09-03T19:05:00.000Z',
    notes: [],
    exercises: [
      workoutExercise('h0903-bench', 'bench-press', [planned('b', 'top_set', 5, undefined, 230)], [
        performed('b1', 'top_set', 230, 5, 8),
        performed('b2', 'backoff', 210, 6),
        performed('b3', 'backoff', 210, 6),
        performed('b4', 'backoff', 210, 6),
      ]),
      workoutExercise('h0903-incline', 'incline-dumbbell-press', [planned('ii', 'working', undefined, [8, 12])], [
        performed('ii1', 'working', 70, 11),
        performed('ii2', 'working', 70, 10),
        performed('ii3', 'working', 70, 9),
      ]),
    ],
  },
  {
    id: 'history-pull-0901',
    date: '2026-09-01',
    title: 'Pull',
    focus: 'Strength',
    estimatedMinutes: 71,
    status: 'completed',
    programDayId: 'pull-strength',
    currentExerciseIndex: 1,
    completedAt: '2026-09-01T18:55:00.000Z',
    notes: [],
    exercises: [
      workoutExercise('h0901-deadlift', 'deadlift', [planned('d', 'top_set', 3, undefined, 455)], [
        performed('d1s', 'top_set', 455, 3, 8.5),
        performed('d2s', 'backoff', 405, 5),
        performed('d3s', 'backoff', 405, 5),
      ]),
    ],
  },
];

export const createInitialGymState = (): GymState => ({
  version: 3,
  today: makeToday(),
  history,
  program,
  preferences: {
    autonomy: 'assist',
    warmups: 'track_if_wanted',
    rpe: 'balanced',
    units: 'lb',
    restTimer: true,
    haptics: true,
    confirmedExerciseDislikes: [],
    unavailableEquipment: ['Hack squat'],
    trainingStyle: ['Top sets + backoffs', 'RPE on main lifts'],
    observedBehaviors: ['Usually skips RPE on accessories'],
  },
  recommendations: [
    {
      id: 'rec-bench-250',
      workoutId: 'workout-2026-09-13',
      exerciseId: 'bench-press',
      kind: 'weight',
      fact: 'You hit 235 × 5 @ 8 last time.',
      recommendation: 'Target 250 × 3 today.',
      rationale: 'Today calls for three reps, and your recent 5-rep bench work has moved from 230 to 235 without a jump in effort.',
      suggestedWeight: 250,
      suggestedReps: 3,
      status: 'active',
      createdAt: '2026-09-13T15:00:00.000Z',
    },
  ],
  interpretations: [],
});

export const warmupSequence = [
  { weight: 135, reps: 8 },
  { weight: 185, reps: 5 },
  { weight: 205, reps: 3 },
  { weight: 225, reps: 1 },
];
